CREATE CONSTRAINT FOR (n:Document)  REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT FOR (n:Chapter)   REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT FOR (n:Paragraph) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT FOR (n:Sentence)  REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT FOR (n:Token)     REQUIRE n.id IS UNIQUE;
